/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Cerberus
 */
public class ProjectAllocationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProjectAllocationFrame
     */
    public ProjectAllocationFrame() {
        initComponents();
        
        ProjectDetailsTextPane.setContentType("text/html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProjectComboBox = new javax.swing.JComboBox<>();
        AllocateButton = new javax.swing.JButton();
        ExportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProjectDetailsTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SMS - Project Allocation");
        setResizable(false);

        ProjectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urisoft E-commerce Website Developement", "Apex PHP Web Application Developement" }));
        ProjectComboBox.setToolTipText("Select Project");
        ProjectComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AllocateButton.setText("Allocate");
        AllocateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AllocateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllocateButtonMouseClicked(evt);
            }
        });

        ExportButton.setText("Export Report");
        ExportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExportButtonMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(ProjectDetailsTextPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ProjectComboBox, 0, 539, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AllocateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExportButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AllocateButton)
                    .addComponent(ExportButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String firstProject = "<div>\n" +
"<div><strong>Project Name:&nbsp;</strong>Urisoft E-commerce Website Developement</div>\n" +
"<br>\n" +
"</div>\n" +
"<div>\n" +
"<div><strong>Project Description:</strong></div>\n" +
"</div>\n" +
"<div>\n" +
"<div>\n" +
"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam volutpat volutpat nisl, sit amet pellentesque dui tincidunt et. Praesent sed arcu euismod, commodo ligula sed, dapibus nunc. Vivamus ac nunc sollicitudin, eleifend mauris in, consequat eros. Nunc vitae condimentum ligula. Pellentesque sit amet augue arcu. Fusce ac tincidunt quam, ut tincidunt risus. Praesent egestas quam eget mi vehicula, ullamcorper mollis lectus tristique. Fusce a metus turpis. Phasellus fermentum, purus id condimentum ultricies, ex massa sollicitudin dolor, a convallis urna turpis at quam. Cras condimentum, lorem ut placerat efficitur, leo magna suscipit odio, id imperdiet velit odio et odio. Donec sodales ornare risus, vel rhoncus leo pharetra non. Duis id arcu et felis laoreet convallis.</p>\n" +
"</div>\n" +
"</div>\n" +
"<div>\n" +
"<p>Donec facilisis velit congue, cursus leo id, fringilla dolor. Donec auctor augue semper nisi dictum bibendum. Aenean venenatis lorem eu sapien venenatis placerat. Maecenas vitae ante nunc. Duis semper semper urna nec fringilla. Vestibulum quis scelerisque massa. Nam dui turpis, convallis vel interdum sed, efficitur imperdiet tellus. Suspendisse sagittis sit amet dui sit amet ultricies. Nunc tincidunt faucibus nunc, eget pulvinar mi auctor finibus.</p>\n" +
"<p><strong>Required Skills:</strong></p>\n" +
"<ul>\n" +
"<li>C#</li>\n" +
"<li>C++</li>\n" +
"<li>Python</li>\n" +
"</ul>\n" +
"<p><strong>Eligible Developers:</strong></p>\n" +
"</div>\n" +
"<div>\n" +
"<ol>\n" +
"<li>Wei Chen (#44123)</li>\n" +
"<li>Emilia Clark (#44009)</li>\n" +
"<li>Mohit Patel (#43887)</li>\n" +
"<li>Alex Mercer (#44002)</li>\n" +
"</ol>\n" +
"</div>";
    
    private String secondProject = "<div>\n" +
"<div><strong>Project Name:&nbsp;</strong>Apex PHP Web Application Developement</div>\n" +
"<div>&nbsp;</div>\n" +
"</div>\n" +
"<div>\n" +
"<div><strong>Project Description:</strong></div>\n" +
"</div>\n" +
"<div>\n" +
"<p>Aenean quis felis non dolor semper iaculis. Vestibulum viverra gravida erat ac aliquam. Quisque eleifend tempus nulla, at pellentesque nunc. Nunc pharetra, dolor volutpat interdum lobortis, diam velit hendrerit mauris, eu volutpat augue leo ac mi. Aenean efficitur sem nisl, eu dapibus justo interdum sit amet. Aenean luctus nec massa ut euismod. Vestibulum sed metus mi. Donec vestibulum lacinia ante, eu suscipit diam commodo at. Ut sed pellentesque tortor, ut aliquam odio.</p>\n" +
"<p>Fusce ut felis luctus, cursus erat ut, tincidunt tortor. Nam ultricies ante orci, sit amet faucibus felis laoreet at. Aliquam erat volutpat. Integer consequat quis orci sed elementum. Sed tortor libero, pharetra quis consequat sed, aliquam id leo. Donec in libero ligula. Nulla venenatis dapibus hendrerit. Curabitur eu est sit amet leo mollis dignissim nec ut quam.</p>\n" +
"<p>Morbi sem felis, pellentesque quis est non, imperdiet bibendum tortor. Integer in aliquam risus, sit amet auctor risus. Phasellus id dolor in metus pretium scelerisque vitae et eros. Duis quis efficitur leo. Vivamus tincidunt non magna at pharetra. Nulla mattis massa lorem, at bibendum nulla tristique id. Proin vulputate arcu eu augue tristique tincidunt. Suspendisse at felis volutpat, rhoncus sapien et, blandit tortor.</p>\n" +
"</div>\n" +
"<div>\n" +
"<p><strong>Required Skills:</strong></p>\n" +
"<ul>\n" +
"<li>PHP</li>\n" +
"<li>Java</li>\n" +
"<li>Python</li>\n" +
"</ul>\n" +
"<p><strong>Eligible Developers:</strong></p>\n" +
"</div>\n" +
"<div>\n" +
"<ol>\n" +
"<li>Morgan White&nbsp;(#44100)</li>\n" +
"<li>Emilia Clark (#44009)</li>\n" +
"<li>Rajesh Gupta (#43993)</li>\n" +
"<li>John Wellick (#44009)</li>\n" +
"<li>Akira Seiko (#42556)</li>\n" +
"</ol>\n" +
"</div>";
    
    private void AllocateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllocateButtonMouseClicked
        switch(ProjectComboBox.getSelectedIndex()){
            case 0:
                ProjectDetailsTextPane.setText(firstProject);
                break;
                
            case 1:
                ProjectDetailsTextPane.setText(secondProject);
                break;
        }
    }//GEN-LAST:event_AllocateButtonMouseClicked

    private void ExportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExportButtonMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("HTML Files", "html");
        fileChooser.setFileFilter(filter);
        if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {          
            FileWriter fileWriter = null;
            try {
                File file = fileChooser.getSelectedFile();
                fileWriter = new FileWriter(file.getAbsoluteFile());
                ProjectDetailsTextPane.write(fileWriter);
                JOptionPane.showMessageDialog(null, "Report successfully exported to " + file.getAbsolutePath(), "Export Successful", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(ProjectAllocationFrame.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fileWriter.close();
                } catch (IOException ex) {
                    Logger.getLogger(ProjectAllocationFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_ExportButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectAllocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectAllocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectAllocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectAllocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectAllocationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllocateButton;
    private javax.swing.JButton ExportButton;
    private javax.swing.JComboBox<String> ProjectComboBox;
    private javax.swing.JTextPane ProjectDetailsTextPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
